# Generated by Django 5.1.3 on 2024-11-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
