# Generated by Django 5.1.3 on 2024-11-30 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_myuser_balance_alter_myuser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='last_name',
        ),
    ]
