# Generated by Django 5.1.3 on 2024-12-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_remove_myuser_first_name_remove_myuser_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('randomCol', models.CharField(max_length=50)),
            ],
        ),
    ]
